# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fcec255d242850d29816f16e0fad35a7cf826cc0bf9ed0dd52e28dcb22347607100dc44a7e7c14b0cdd41802775f87c5c73a4d53b1a9459f6aea20ee242f307

test:
  secret_key_base: 5e4d219c162e80f87cf83e28d5f372aaedf14c1478406482f4d567b7b5c620333959717a76761b1e67566756367c493f7d8db68a1952a15fa44018a94043f641

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
